-- MySQL Script generated by MySQL Workbench
-- Mon Sep 15 10:09:55 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`alerta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`alerta` (
  `IdAlerta` INT NOT NULL AUTO_INCREMENT,
  `Data` DATE NOT NULL,
  `Mensagem` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`IdAlerta`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mydb`.`planos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`planos` (
  `IdPlano` INT NOT NULL AUTO_INCREMENT,
  `Tipo` VARCHAR(45) NOT NULL,
  `Preco` FLOAT NOT NULL,
  PRIMARY KEY (`IdPlano`),
  UNIQUE INDEX `Tipo_UNIQUE` (`Tipo` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mydb`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuarios` (
  `IdUsuario` INT NOT NULL AUTO_INCREMENT,
  `CPF` VARCHAR(11) NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Sobrenome` VARCHAR(45) NOT NULL,
  `DataNascimento` DATETIME NOT NULL,
  `Email` VARCHAR(60) NOT NULL,
  `Genero` VARCHAR(45) NOT NULL,
  `Senha` VARCHAR(45) NOT NULL,
  `Tipo` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`IdUsuario`),
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC) VISIBLE,
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mydb`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`clientes` (
  `IdCliente` INT NOT NULL AUTO_INCREMENT,
  `CPF` VARCHAR(11) NOT NULL,
  `DataAssinatura` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `idPlano` VARCHAR(40) NULL DEFAULT NULL,
  `Altura` FLOAT NOT NULL,
  `Peso` FLOAT NULL,
  `Experiencia` VARCHAR(45) NULL,
  `EspecificacoesMedicas` VARCHAR(225) NULL,
  `Medicamentos` VARCHAR(225) NULL,
  `Limitacoes` VARCHAR(225) NULL,
  `PctgmGordura` FLOAT NULL,
  PRIMARY KEY (`IdCliente`),
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC) VISIBLE,
  INDEX `idPlano` (`idPlano` ASC) VISIBLE,
  CONSTRAINT `clientes_ibfk_1`
    FOREIGN KEY (`idPlano`)
    REFERENCES `mydb`.`planos` (`Tipo`),
  CONSTRAINT `fk_cliente_usuario`
    FOREIGN KEY (`CPF`)
    REFERENCES `mydb`.`usuarios` (`CPF`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mydb`.`instrutores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`instrutores` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `salario` DECIMAL(10,2) NULL DEFAULT NULL,
  `formacao` VARCHAR(250) NULL DEFAULT NULL,
  `associado` VARCHAR(45) NULL DEFAULT NULL,
  `entrada` TIME NULL DEFAULT NULL,
  `saida` TIME NULL DEFAULT NULL,
  `CPF` VARCHAR(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `CPF` (`CPF` ASC) VISIBLE,
  CONSTRAINT `instrutores_ibfk_1`
    FOREIGN KEY (`CPF`)
    REFERENCES `mydb`.`usuarios` (`CPF`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
