-- MySQL Script generated by MySQL Workbench
-- Wed Aug 20 11:20:47 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema GodOfTheGym
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema GodOfTheGym
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `GodOfTheGym` DEFAULT CHARACTER SET utf8 ;
USE `GodOfTheGym` ;

-- -----------------------------------------------------
-- Table `GodOfTheGym`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GodOfTheGym`.`Usuarios` (
  `CPF` DECIMAL(11,0) NOT NULL,
  `IdUsuario` INT GENERATED ALWAYS AS () VIRTUAL,
  `Nome` VARCHAR(45) NOT NULL,
  `Sobrenome` VARCHAR(45) NOT NULL,
  `DataNascimento` DATETIME NOT NULL,
  `Email` VARCHAR(60) NOT NULL,
  `Genero` VARCHAR(45) NOT NULL,
  `Senha` VARCHAR(45) NOT NULL,
  UNIQUE INDEX `IdUsuario_UNIQUE` (`IdUsuario` ASC) VISIBLE,
  UNIQUE INDEX `Gmail_UNIQUE` (`Email` ASC) VISIBLE,
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC) VISIBLE,
  PRIMARY KEY (`CPF`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GodOfTheGym`.`Gerente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GodOfTheGym`.`Gerente` (
  `CPF` DECIMAL(11,0) NOT NULL,
  `IdGerente` INT GENERATED ALWAYS AS () VIRTUAL,
  UNIQUE INDEX `IdGerente_UNIQUE` (`IdGerente` ASC) VISIBLE,
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC) VISIBLE,
  PRIMARY KEY (`CPF`),
  CONSTRAINT `CPF`
    FOREIGN KEY (`CPF`)
    REFERENCES `GodOfTheGym`.`Usuarios` (`CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GodOfTheGym`.`Planos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GodOfTheGym`.`Planos` (
  `Tipo` VARCHAR(45) NOT NULL,
  `Preco` FLOAT NOT NULL,
  PRIMARY KEY (`Tipo`),
  UNIQUE INDEX `Tipo_UNIQUE` (`Tipo` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GodOfTheGym`.`Recepcionista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GodOfTheGym`.`Recepcionista` (
  `CPF` DECIMAL(11,0) NOT NULL,
  `IdRecepcionista` INT GENERATED ALWAYS AS () VIRTUAL,
  PRIMARY KEY (`CPF`),
  UNIQUE INDEX `IdRecepcionista_UNIQUE` (`IdRecepcionista` ASC) VISIBLE,
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC) VISIBLE,
  CONSTRAINT `CPF`
    FOREIGN KEY (`CPF`)
    REFERENCES `GodOfTheGym`.`Usuarios` (`CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GodOfTheGym`.`Alerta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GodOfTheGym`.`Alerta` (
  `IdAlerta` INT GENERATED ALWAYS AS () VIRTUAL,
  `Data` DATE NOT NULL,
  `Mensagem` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`IdAlerta`),
  UNIQUE INDEX `Data_UNIQUE` (`Data` ASC) VISIBLE,
  UNIQUE INDEX `IdAlerta_UNIQUE` (`IdAlerta` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GodOfTheGym`.`Clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GodOfTheGym`.`Clientes` (
  `idClientes` INT GENERATED ALWAYS AS () VIRTUAL,
  `CPF` DECIMAL(11,0) NOT NULL,
  `DataAssinatura` DATE NOT NULL,
  PRIMARY KEY (`CPF`),
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC) VISIBLE,
  UNIQUE INDEX `DataAssinatura_UNIQUE` (`DataAssinatura` ASC) VISIBLE,
  UNIQUE INDEX `idClientes_UNIQUE` (`idClientes` ASC) VISIBLE,
  CONSTRAINT `CPF`
    FOREIGN KEY (`CPF`)
    REFERENCES `GodOfTheGym`.`Usuarios` (`CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GodOfTheGym`.`Instrutores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GodOfTheGym`.`Instrutores` (
  `Salario` FLOAT NOT NULL,
  `CPF` DECIMAL(11,0) NOT NULL,
  `IdInstrutor` INT GENERATED ALWAYS AS () VIRTUAL,
  `CargaHoraria` FLOAT NOT NULL,
  PRIMARY KEY (`CPF`),
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC) VISIBLE,
  UNIQUE INDEX `IdInstrutor_UNIQUE` (`IdInstrutor` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
